version: 2

sphinx:
  builder: html
  configuration: pylace/docs/source/conf.py

build:
  # readdocs master now includes a rust toolchain
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
    rust: "1.64"

python:
  install:
    - requirements: pylace/docs/requirements.txt
    - method: pip
      path: pylace
