version: 2

sphinx:
  builder: html
  configuration: pylace/docs/source/conf.py

build:
  # readdocs master now includes a rust toolchain
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
    rust: "1.64"
  jobs:
    post_install:
      - pip install maturin pyarrow polars pandas scipy plotly tqdm
      - maturin build --release -m pylace/core/Cargo.toml --out dist
      - pip install pybraid_core --no-index --find-links dist --force-reinstall
      - pip install ./pylace
